export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
export const FACEBOOK_LOGIN_FAIL = "FACEBOOK_LOGIN_FAIL";
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const YELP_AUTH = 'Bearer _EFprt7GDY0aJU4gnGmMPBL18kJkBsJHckQyweV6ne8Gx03l2KEZDvJztUxh6QGutjNnT38xTgXzmUZfzwbx8XBsU9fqoe8YuBSZLoiFS0RdJ3qT3rVIFzbV-nfVWXYx';